#!/bin/sh

echo "init frontpanel"
modprobe proton
modprobe simu_button
   echo "ОЖИДАЙТЕ" > /dev/vfd
   echo "ОЖИДАЙТЕ 1мин"
if [ -e /var/etc/.firstboot ]; then
   rm /var/etc/.firstboot
   touch /dev/.devfsd
fi

/etc/init.d/mountvirtfs start

   modprobe e2_proc

if [ ! -e /var/etc/.firstboot ]; then

   echo "init stmfb"
   modprobe stmcore-display-stx7109c3
   modprobe stmfb display0=1920x1080-32@50:12m:pal:yuv:yuv

   echo "LOADING MODULES"   
   echo "ЗАГРУЗКА" >/dev/vfd

   /bin/ustslave /dev/st231-1 /boot/audio.elf
   echo "load v firmware"
   /bin/ustslave /dev/st231-0 /boot/video.elf

   echo "init embx"
   modprobe embxshell
   modprobe embxmailbox mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
   modprobe embxshm mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
   modprobe mme_host transport0=shm

   echo "init AVS"
   modprobe avs type=stv6418

   modprobe mmelog
   modprobe mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
   modprobe ksound
   modprobe p2div64
   modprobe stm_v4l2
   modprobe pseudocard

   modprobe fe-core demod=stb0899 tuner=stb6100
   modprobe pti waitMS=20 videoMem=10240
   modprobe stm_monitor
   modprobe stmsysfs
   modprobe stmdvb

   modprobe player2 discardlateframe=0
   modprobe sth264pp
   modprobe stmalloc
   modprobe platform
   modprobe silencegen
   modprobe smartcard debug=100
   modprobe bpamem
   echo "init oc"
   modprobe cpu_frequ
   #405mhz
   #echo 25609 > /proc/cpu_frequ/pll0_ndiv_mdiv
   #echo 1 > /proc/cpu_frequ/pll1_fdma_bypass
   #15110 = 266mhz
   #25609 = 300mhz
   #9475 = 333mhz
   #31241 = 366mhz
   #22790 = 400mhz
   #3841 = 405mhz

   echo "init lircd"
   /usr/bin/lircd

   mknod /dev/rc c 147 1 
   mknod /dev/sci0 c 169 0
   mknod /dev/sci1 c 169 1 
   
   /bin/evremote2 hl101 &

   /etc/init.d/mountall start
   /etc/init.d/hostname start

   echo "starting telnetd"
   /usr/sbin/telnetd -l /bin/login
   /etc/init.d/vsftpd start
   /usr/sbin/inetd
 
   if [ -e /etc/network/interfaces ]; then 
	 ip addr flush eth0 
	 /etc/init.d/networking stop 
	 DHCP=`grep -c dhcp /etc/network/interfaces`
   if [ "$DHCP" -eq "1" ]; then 
	    echo "Starting dhcp"
            /etc/init.d/udhcpc start 
   fi 
	 /etc/init.d/networking start 
   fi

   touch /dev/.udev

   echo "ЭНИГМА" > /dev/vfd
   echo "LOADING RUNIGMA"

   until false
   do

   
    /var/bin/swap start
    /var/bin/on_gmt.sh
    /var/bin/emustarter.sh &
    /var/bin/opkg.sh &
   
    #mount /dev/sdb1 /media/hdd/movie
   
    showiframe -p /boot/bootlogo.mvi &
    stfbcontrol a 0

	stfbcontrol a 255
	echo " e2 "
      /usr/local/bin/enigma2
  
      rtv=$?
      echo "e2 ended <- RTV: " $rtv
      case "$rtv" in
		0) echo "0"
		   echo "E2 ERROR"
           echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-03-rebootGUI.mvi &;;
		1) echo "1"
		   echo "SHUTDOWN"
		   /bin/shutdown.sh;;
		2) echo "2"
		   echo "REBOOT"
           showiframe -p /boot/RUnigmaHD-VIP-03-reboot.mvi &
           /etc/init.d/reboot;;
		3) echo "3"
		   echo "E2 RESTART"
		   echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-03-rebootGUI.mvi &;;
		*) echo "*"
		   echo "ERROR"
           echo "0" > /proc/progress
		   showiframe -p /boot/RUnigmaHD-VIP-03-rebootGUI.mvi &;;
      esac
   done 
fi

#never reached
echo "REBOOT HL101" > /dev/vfd
echo "REBOOT HL101"
reboot 
